"""真实岗位数据源配置。

每个源定义包含：
- name: 数据源名称
- type: 采集类型 (rss / seed / domestic_web)
- url: 公开 RSS 地址（rss 类型）
- parser: 解析方式 (rss_atom)（rss 类型）
- description: 数据源说明
- requires_filter: 是否需要从通用内容中过滤出招聘帖

国内平台源（domestic_web）默认关闭，避免开发/测试环境误触发反爬。
"""

from typing import Any

SOURCES: list[dict[str, Any]] = [
    {
        "name": "v2ex_jobs",
        "type": "rss",
        "url": "https://www.v2ex.com/feed/jobs.xml",
        "parser": "rss_atom",
        "description": "V2EX 酷工作节点 RSS，中文技术岗位公开源",
        "requires_filter": False,
    },
    {
        "name": "ruby_china_jobs",
        "type": "rss",
        "url": "https://ruby-china.org/topics/feed",
        "parser": "rss_atom",
        "description": "Ruby China 社区话题 RSS，偶含技术岗位",
        "requires_filter": True,
    },
    {
        "name": "learnku_python_jobs",
        "type": "rss",
        "url": "https://learnku.com/python/feed",
        "parser": "rss_atom",
        "description": "LearnKu Python 社区 RSS，含招聘/求职帖",
        "requires_filter": True,
    },
    {
        "name": "learnku_laravel_jobs",
        "type": "rss",
        "url": "https://learnku.com/laravel/feed",
        "parser": "rss_atom",
        "description": "LearnKu Laravel 社区 RSS，含 PHP/前端岗位帖",
        "requires_filter": True,
    },
    {
        "name": "learnku_go_jobs",
        "type": "rss",
        "url": "https://learnku.com/go/feed",
        "parser": "rss_atom",
        "description": "LearnKu Go 社区 RSS，含 Go 岗位帖",
        "requires_filter": True,
    },
    {
        "name": "cnodejs",
        "type": "rss",
        "url": "https://cnodejs.org/rss",
        "parser": "rss_atom",
        "description": "CNode 社区 RSS，Node.js 技术社区偶含招聘帖",
        "requires_filter": True,
    },
    {
        "name": "oschina_news",
        "type": "rss",
        "url": "https://www.oschina.net/news/rss",
        "parser": "rss_atom",
        "description": "开源中国资讯 RSS，技术行业动态含招聘信号",
        "requires_filter": True,
    },
    {
        "name": "segmentfault",
        "type": "rss",
        "url": "https://segmentfault.com/feeds",
        "parser": "rss_atom",
        "description": "思否社区 RSS，开发者社区含招聘/求职内容",
        "requires_filter": True,
    },
    {
        "name": "infoq_cn",
        "type": "rss",
        "url": "https://www.infoq.cn/feed",
        "parser": "rss_atom",
        "description": "InfoQ 中文站 RSS，技术行业动态含招聘信号",
        "requires_filter": True,
    },
    {
        "name": "cnblogs",
        "type": "rss",
        "url": "https://www.cnblogs.com/rss",
        "parser": "rss_atom",
        "description": "博客园 RSS，开发者社区含招聘/求职内容",
        "requires_filter": True,
    },
    # -----------------------------------------------------------------------
    # 国内招聘平台公开列表页（默认关闭，需同时开启配置 DOMESTIC_CRAWLER_ENABLED）
    # -----------------------------------------------------------------------
    {
        "name": "boss_zhipin_python_beijing",
        "type": "domestic_web",
        "platform": "boss",
        "enabled": False,
        "base_url": "https://www.zhipin.com",
        "search_url_template": "https://www.zhipin.com/web/geek/job?query={keyword}&city={city}",
        "city_code": "101010100",
        "keyword": "Python",
        "job_selector": [".job-card-wrapper", ".job-card-pc", "li.job-card-pc"],
        "description": "Boss 直聘北京 Python 岗位（Playwright 抓取，反爬强默认关闭）",
    },
    {
        "name": "boss_zhipin_python_shanghai",
        "type": "domestic_web",
        "platform": "boss",
        "enabled": False,
        "base_url": "https://www.zhipin.com",
        "search_url_template": "https://www.zhipin.com/web/geek/job?query={keyword}&city={city}",
        "city_code": "101020100",
        "keyword": "Python",
        "job_selector": [".job-card-wrapper", ".job-card-pc", "li.job-card-pc"],
        "description": "Boss 直聘上海 Python 岗位（Playwright 抓取，反爬强默认关闭）",
    },
    {
        "name": "boss_zhipin_java_beijing",
        "type": "domestic_web",
        "platform": "boss",
        "enabled": False,
        "base_url": "https://www.zhipin.com",
        "search_url_template": "https://www.zhipin.com/web/geek/job?query={keyword}&city={city}",
        "city_code": "101010100",
        "keyword": "Java",
        "job_selector": [".job-card-wrapper", ".job-card-pc", "li.job-card-pc"],
        "description": "Boss 直聘北京 Java 岗位（Playwright 抓取，反爬强默认关闭）",
    },
    {
        "name": "boss_zhipin_frontend_beijing",
        "type": "domestic_web",
        "platform": "boss",
        "enabled": False,
        "base_url": "https://www.zhipin.com",
        "search_url_template": "https://www.zhipin.com/web/geek/job?query={keyword}&city={city}",
        "city_code": "101010100",
        "keyword": "前端开发",
        "job_selector": [".job-card-wrapper", ".job-card-pc", "li.job-card-pc"],
        "description": "Boss 直聘北京前端开发岗位（Playwright 抓取，反爬强默认关闭）",
    },
    {
        "name": "boss_zhipin_go_beijing",
        "type": "domestic_web",
        "platform": "boss",
        "enabled": False,
        "base_url": "https://www.zhipin.com",
        "search_url_template": "https://www.zhipin.com/web/geek/job?query={keyword}&city={city}",
        "city_code": "101010100",
        "keyword": "Go",
        "job_selector": [".job-card-wrapper", ".job-card-pc", "li.job-card-pc"],
        "description": "Boss 直聘北京 Go 岗位（Playwright 抓取，反爬强默认关闭）",
    },
    {
        "name": "zhilian_python_beijing",
        "type": "domestic_web",
        "platform": "zhilian",
        "enabled": True,
        "base_url": "https://www.zhaopin.com",
        "search_url_template": "https://sou.zhaopin.com/?jl={city}&kw={keyword}",
        "city_code": "530",
        "keyword": "Python",
        "job_selector": [".joblist-box__item", ".joblist-box__iteminfo"],
        "description": "智联招聘北京 Python 岗位（Playwright 抓取）",
    },
    {
        "name": "zhilian_java_beijing",
        "type": "domestic_web",
        "platform": "zhilian",
        "enabled": True,
        "base_url": "https://www.zhaopin.com",
        "search_url_template": "https://sou.zhaopin.com/?jl={city}&kw={keyword}",
        "city_code": "530",
        "keyword": "Java",
        "job_selector": [".joblist-box__item", ".joblist-box__iteminfo"],
        "description": "智联招聘北京 Java 岗位（Playwright 抓取）",
    },
    {
        "name": "zhilian_frontend_beijing",
        "type": "domestic_web",
        "platform": "zhilian",
        "enabled": True,
        "base_url": "https://www.zhaopin.com",
        "search_url_template": "https://sou.zhaopin.com/?jl={city}&kw={keyword}",
        "city_code": "530",
        "keyword": "前端开发",
        "job_selector": [".joblist-box__item", ".joblist-box__iteminfo"],
        "description": "智联招聘北京前端开发岗位（Playwright 抓取）",
    },
]
